#
# for huaqin misc info
#

# Huaqin add for ZQL1830-235 by liunianliang at 2018/07/05 start
obj-$(CONFIG_HQ_SIM_TRAY_CHECK)   += sim_tray/
# Huaqin add for ZQL1830-235 by liunianliang at 2018/07/05 end

# Huaqin add for ZQL1830-278 by diganyun at  2018/08/14 start
obj-$(CONFIG_HQ_HARDWARE_INFO)   += hardware_info/
# Huaqin add for ZQL1830-278 by diganyun at 2018/08/14 end
