#
# for huaqin hardware info
#

# Huaqin add for ZQL1830-278 by diganyun at 2018/08/14 start
obj-$(CONFIG_HQ_HARDWARE_INFO) += hardwareInfo.o
# Huaqin add for ZQL1830-278 by diganyun at 2018/08/14 end
